image: Visual Studio 2019 

install:
  - C:/Python37-x64/python.exe -m pip install -U --progress-bar off pip setuptools wheel
  - C:/Python37-x64/python.exe -m pip install -U --progress-bar off scons pypiwin32 colorama
  - git submodule update --init --recursive

build: off
build_script:
  - C:/Python37-x64/Scripts/scons.bat
  - C:/Python37-x64/Scripts/scons.bat -c
  - git submodule foreach git pull origin master
  - C:/Python37-x64/Scripts/scons.bat
