matrix:
  include:
    - os: linux
      dist: trusty
      python: '3.5'
      env: 
        - PYTHONCOM=python
        - PYTHON_VERSION=3.5
    - os: linux
      dist: trusty
      python: '2.7'
      env: 
        - PYTHONCOM=python
        - PYTHON_VERSION=2.7
      
install:
  - cd ${TRAVIS_BUILD_DIR}
  # install latest LCOV (1.9 was failing for me) [1]
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov
  - python -m pip install -U --progress-bar off pip setuptools wheel
  - python -m pip install -U --progress-bar off scons

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}
  - scons --cover
  - ./build/infcover

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls