os: linux
language: python

matrix:
  include:
    - dist: trusty
      python: '3.6'
    - dist: xenial
      python: '3.7'
    - dist: bionic
      python: '3.7'
   
install:
  - cd ${TRAVIS_BUILD_DIR}
  # install latest LCOV (1.9 was failing for me) [1]
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov
  - pip install -U pip setuptools wheel
  - pip install -U scons

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}
  - scons 
  - scons -c
  - git submodule foreach git pull origin master
  - scons --cover
  - ./build/infcover

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
