matrix:
  include:
    - os: linux
      dist: trusty
      python: '3.5'
      env: 
        - PYTHONCOM=python
        - PYTHON_VERSION=3.5
    - os: linux
      dist: trusty
      python: '2.7'
      env: 
        - PYTHONCOM=python
        - PYTHON_VERSION=2.7
    - os: osx
      python: '3.5' 
      env: 
        - PYTHONCOM=python
        - PYTHON_VERSION=3.5
    - os: osx
      python: '2.7'
      env: 
        - PYTHONCOM=python
        - PYTHON_VERSION=2.7
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == "3.5" ]]; then sudo add-apt-repository -y ppa:deadsnakes/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == "3.5" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == "3.5" ]]; then sudo apt-get -y install python3.5 python3-pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == "2.7" ]]; then sudo apt-get -y install python-pip python-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == "2.7" ]]; then sudo pip install --egg SCons; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON_VERSION" == "3.5" ]]; then sudo pip3 install --egg SCons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "2.7" ]]; then sudo /usr/local/bin/pip install --egg SCons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.5" ]]; then brew install python3; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.5" ]]; then sudo /usr/local/bin/pip3 install --egg SCons; fi 
    
script: 
  - scons